packages:
    - packages/*
catalog:
    "@changesets/cli": ^2.27.12
    "@commitlint/cli": ^19.6.1
    "@commitlint/config-conventional": ^19.6.0
    "@microsoft/api-extractor": ^7
    "@testing-library/dom": ^10
    "@testing-library/jest-dom": ^6
    "@testing-library/react": ^16
    "@testing-library/user-event": ^14
    "@types/node": ^22
    "@types/react": ^19
    "@types/react-dom": ^19
    "@vitejs/plugin-react": ^4
    "@vitest/coverage-istanbul": ^3
    eslint: ^8
    eslint-config-react-app: ^7
    husky: ^9.1.7
    jsdom: ^26
    lint-staged: ^16
    prettier: ^3
    react: ^19
    react-dom: ^19
    typescript: ^5
    vite: ^6
    vite-plugin-dts: ^4
    vitest: ^3
